#!/usr/bin/env php
<?php

/**
 * This file is part of the symfony package.
 * (c) Fabien Potencier <fabien.potencier@symfony-project.com>
 * 
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * Proyecto generado, configurado e instalado con el nombre:
 * 
 * dml3
 *
 * @author  Oswaldo Rojas <def.3980@gmail.com>
 * @fecha   Martes, 13 Diciembre 2016 23:27:24
 */
chdir(dirname(__FILE__));
require_once(dirname(__FILE__).'/config/ProjectConfiguration.class.php');
include(sfCoreAutoload::getInstance()->getBaseDir().'/command/cli.php');